# This is a basic workflow that is manually triggered

name: Check if file is valid

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
#     # Inputs the workflow accepts.
#     inputs:
#       name:
#         # Friendly description to be shown in the UI instead of 'name'
#         description: 'Enter command:'
#         # Default value if no value is explicitly provided
#         default: 'validate'
#         # Input has to be provided for the workflow to run
#         required: true
env:
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
    # Runs a single command using the runners shell
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Validate file
        run: python main.py -v
